# Generated by Django 4.2.23 on 2025-07-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250713_1432'),
        ('blog', '0004_auto_20250713_1433'),
    ]

    operations = [
    ]
