# Generated by Django 4.2.23 on 2025-07-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_0003_auto_20250713_1432_0004_auto_20250713_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
