# Generated by Django 4.2.23 on 2025-07-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
